<a href="https://colab.research.google.com/github/MunishUpadhyay/NumPy/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical python

Advantages of NumPy Array

1. Allows several mathematical operations

2. Faster operations

In [ ]:
import numpy as np

Types of arrays:-

One dimensional array

Two dimensional array

In [ ]:
np_array = np.array([1,2,3,4,5])  # default data type is integer
print(np_array)
np_array.shape

[1 2 3 4 5]


(5,)

In [ ]:
np_array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype = float)
print(np_array1)
np_array1.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

Initial Placeholders in numpy array

In [ ]:
# numpy array of zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# numpy array of ones
b = np.ones((5,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# array of a particular value
c = np.full((4,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# array with random inputs ranging from 0-1
e = np.random.random((3,3))
print(e)

[[0.40269002 0.15593607 0.77732479]
 [0.1986209  0.61818979 0.40403643]
 [0.45416233 0.04539891 0.21760774]]


In [ ]:
# array with random integer values
f = np.random.randint(10,100,(3,4))
print(f)

[[31 27 71 48]
 [55 14 21 33]
 [45 39 85 94]]


In [ ]:
# array with evenly spaced values --> specifying the number of values required
g = np.linspace(10,30,5)
print(g)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
h = np.arange(10,30,5)
print(h)

[10 15 20 25]


In [ ]:
# converting a list to a numpy array
i = [1,2,3,4,5]
j = np.asarray(i)
print(j)
type(j)

[1 2 3 4 5]


numpy.ndarray

Analysing a numpy array

In [ ]:
np_array = np.random.randint(10,90,(5,5))
print(np_array)

[[54 66 73 81 89]
 [37 81 68 39 19]
 [66 45 86 16 40]
 [29 12 29 68 33]
 [75 10 46 89 44]]


In [ ]:
# array dimension
print(np_array.shape)

(5, 5)


In [ ]:
# number of dimension
print(np_array.ndim)

2


In [ ]:
# number of elements in an array
print(np_array.size)

25


In [ ]:
# checking the type of data in an array
print(np_array.dtype)

int64


Mathematical operations on a numpy array

In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 5 5]
 [0 8 2]
 [8 8 6]]
[[15 16 16]
 [13 17 16]
 [18 14 19]]


In [ ]:
print(a+b)
print()
print(a-b)
print()
print(a*b)
print()
print(a/b)

[[20 21 21]
 [13 25 18]
 [26 22 25]]

[[-10 -11 -11]
 [-13  -9 -14]
 [-10  -6 -13]]

[[ 75  80  80]
 [  0 136  32]
 [144 112 114]]

[[0.33333333 0.3125     0.3125    ]
 [0.         0.47058824 0.125     ]
 [0.44444444 0.57142857 0.31578947]]


In [ ]:
print(a)
print()
print(b)

[[5 5 5]
 [0 8 2]
 [8 8 6]]

[[15 16 16]
 [13 17 16]
 [18 14 19]]


In [ ]:
print(np.add(a,b))
print()
print(np.subtract(a,b))
print()
print(np.multiply(a,b))
print()
print(np.divide(a,b))

[[20 21 21]
 [13 25 18]
 [26 22 25]]

[[-10 -11 -11]
 [-13  -9 -14]
 [-10  -6 -13]]

[[ 75  80  80]
 [  0 136  32]
 [144 112 114]]

[[0.33333333 0.3125     0.3125    ]
 [0.         0.47058824 0.125     ]
 [0.44444444 0.57142857 0.31578947]]


Array Manipulation

In [ ]:
# transpose of a matrix
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 4 0]
 [2 3 3]]
(2, 3)


In [ ]:
np_transpose = array.T   # can also be done using array.transpose
print(np_transpose)
print(np_transpose.shape)

[[7 2]
 [4 3]
 [0 3]]
(3, 2)


In [ ]:
# reshaping of a matrix
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 8 8]
 [4 4 9]]
(2, 3)


In [ ]:
array = a.reshape(3,2)
print(array)
print(array.shape)

[[4 8]
 [8 4]
 [4 9]]
(3, 2)
